name: data

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  poll_transform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Poll & Transform
      run: |
        cd script && python3 main.py && cd ..
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Set variable to check if anything changed
      id: is_updated
      run: |-
        echo "##[set-output name=changed;]$(git diff --quiet HEAD public/*.json; echo $?)"
    - name: Commit files
      if: steps.is_updated.outputs.changed != 0
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public
        git commit -m "Update at $(date +'%Y-%m-%d %H:%M')"
    - name: Push changes
      if: steps.is_updated.outputs.changed != 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
